# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testeCalculadoraInvestimento' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testeCalculadoraInvestimento
  pod 'SwiftLint'
  pod 'PKHUD', '~> 5.0'
end
